### ISSUE TITLE
Investments: sETH/ETH wrong value

### ISSUE THREAD

**Issue by milkyklim** [Destiner/Portle#2]
sETH/ETH Uniswap liquidity pool in `Investments` section shows wrong value. 

I suspect ETH and sETH parts should be divided by `1000` to give the correct value.

**Comment by Destiner** [comment]
Hey. I checked some accounts that pooled to sETH/ETH on Uniswap and the value of their pool holdings seems to be ok. Is the price shown as ~$535 (on the bottom left)? Does it show the correct amount of tokens (e.g. same as on Etherscan)?

If you could provide an address that shows incorrect value of any Uniswap pool that would be nice.

**Comment by milkyklim** [comment]
E.g. this one: https://portle.io/wallet/0x85c7942567a64f442a710d6259806db4ae29f3b6/investment/uniswap/seth_eth. 

This is what I see on mozilla: 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/10698619/75116992-fa5c5300-566d-11ea-8dfe-3a688c8d655d.png">
The price you've mentioned seems to be right. 

Is this related to the fact that LP should stake their tokens in another contract now (see https://blog.synthetix.io/new-uniswap-seth-lp-reward-system)?

**Comment by Destiner** [comment]
Alright so there seems to be an issue with Uniswap subgraph that Portle uses. I submitted an [issue](https://github.com/graphprotocol/uniswap-subgraph/issues/27). If the issue will persist I'll use different source.

**Comment by Destiner** [comment]
The problem with the underlying subgraph was fixed. I checked a few addresses and they seem good.

I'm closing this. Feel free to create a new issue if there's something wrong with uniswap or other protocol.

**Comment by milkyklim** [comment]
Confirm, working on my side. Thank you!
